[package]
name = "fjall-morphology-python"
version = "0.1.0"
edition = "2024"

[lib]
name = "_core"
# "cdylib" is necessary to produce a shared library for Python to import from.
crate-type = ["cdylib"]

[dependencies]
fjall-morphology-core = { workspace = true }
pyo3 = { workspace = true }
